### ISSUE TITLE
Not meant to work on stable?

### ISSUE THREAD

**Issue by Keats** [valeriansaliou/rs-card-validate#2]
I'm using card-validate and the current version doesn't compile on stable Rust and there is no stable testing on travis? Is this crate meant to be nightly only?

From https://github.com/Keats/validator/issues/35

**Comment by valeriansaliou** [comment]
Bumped `rs-card-validate` to [06a7c5fa95173cf421888f9df6edc3e5d4519947](https://github.com/valeriansaliou/rs-card-validate/commit/06a7c5fa95173cf421888f9df6edc3e5d4519947).

Thanks!
