### ISSUE TITLE
Making validation functions public/accessible

### ISSUE THREAD

**Issue by rohitjoshi** [valeriansaliou/rs-card-validate#4]
Can you make `is_luhn_valid()`, `is_length_valid()` and `evaluate_type()` public so we can selectively invoke specific type of validation?

Also, it would be helpful validation at the bin  (first 6 digits) level.

**Comment by valeriansaliou** [comment]
Hi!

Would it be better for you if the returned result contains those sub-values? This would be handier than calling each specific functions once again; as when you validate a card they are called (this would avoid extra-computations, but I’m being picky there).

--

Valerian Saliou
CTO at Crisp <https://crisp.chat/> & Enrich <https://enrichdata.com/> — About me <https://valeriansaliou.name/>

**Comment by valeriansaliou** [comment]
Thanks. Accepted your MR anyway, that's probably the best way to do it.

Just released `v2.1.6` on Crates.io.

**Comment by rohitjoshi** [comment]
Thanks 👍
